apiVersion: v1
kind: ConfigMap
metadata:
  name: db-and-kafka-config
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "summaries_db"
  KAFKA_HOST: "kafka"
  KAFKA_PORT: "9092"
